export default [
  {
    id: '1',
    name: 'Gato que Late',
    street: 'Rua dos cachorros bravos',
    number: '1234',
    district: 'Gatinho manhoso',
    city: 'Franca',
    uf: 'SP',
    donationCode: 'o319h3po21i3ut21y039uog321o83712igo3127312of31',
  },
  {
    id: '2',
    name: 'Passaro que não voa',
    street: 'Praça dos tucanos',
    number: '431',
    district: 'Centro',
    city: 'Franca',
    uf: 'SP',
    donationCode: 'passaro@voasim.com.br',
  },
  {
    id: '3',
    name: 'Patinha de bronze',
    street: 'Av. salve as patas',
    number: '3214',
    district: 'Aeroporto',
    city: 'Ribeirão-Preto',
    uf: 'SP',
    donationCode: '98372197d1ínpi1poje12hg312voi12uy9duo19d7hiu',
  },
  {
    id: '4',
    name: 'Nem Noé',
    street: 'Rua da arca',
    number: '998',
    district: 'Vila salva vidas',
    city: 'Rio de Janeiro',
    uf: 'RJ',
    donationCode: 'udhadawouidPJDAWIDOaoijdoaijdawJDWPAIÒI654746',
  },
  {
    id: '5',
    name: 'Lagoa azul',
    street: 'Praça da ilha perdida',
    number: '58',
    district: 'Hollywood',
    city: 'São Paulo',
    uf: 'SP',
    donationCode: '712igpjawkj81j3h12i312hodhuPIOUIDUIDWDGAUodayo',
  },
  
]
